# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblaze/microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze || ORIG_REF_NAME==microblaze}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_4/microblaze_microblaze_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_4 || ORIG_REF_NAME==microblaze_microblaze_0_4}]

# IP: bd/microblaze/ip/microblaze_mig_7series_0_0/microblaze_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_mig_7series_0_0 || ORIG_REF_NAME==microblaze_mig_7series_0_0}]

# IP: bd/microblaze/ip/microblaze_dlmb_v10_0/microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_0 || ORIG_REF_NAME==microblaze_dlmb_v10_0}]

# IP: bd/microblaze/ip/microblaze_ilmb_v10_0/microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_0 || ORIG_REF_NAME==microblaze_ilmb_v10_0}]

# IP: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_0/microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_dlmb_bram_if_cntlr_0}]

# IP: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_ilmb_bram_if_cntlr_0}]

# IP: bd/microblaze/ip/microblaze_lmb_bram_0/microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_lmb_bram_0 || ORIG_REF_NAME==microblaze_lmb_bram_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_periph_0/microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_microblaze_0_axi_periph_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_0/microblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_xlconcat_0/microblaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microblaze_microblaze_0_xlconcat_0}]

# IP: bd/microblaze/ip/microblaze_rst_mig_7series_0_100M_0/microblaze_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==microblaze_rst_mig_7series_0_100M_0}]

# IP: bd/microblaze/ip/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_axi_timer_0_0 || ORIG_REF_NAME==microblaze_axi_timer_0_0}]

# IP: bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_axi_uartlite_0_0}]

# IP: bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xbar_0 || ORIG_REF_NAME==microblaze_xbar_0}]

# IP: bd/microblaze/ip/microblaze_axi_bram_ctrl_0_0/microblaze_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_axi_bram_ctrl_0_0 || ORIG_REF_NAME==microblaze_axi_bram_ctrl_0_0}]

# IP: bd/microblaze/ip/microblaze_blk_mem_gen_0_0/microblaze_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_blk_mem_gen_0_0 || ORIG_REF_NAME==microblaze_blk_mem_gen_0_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_1 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_1}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_0/microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_0 || ORIG_REF_NAME==microblaze_microblaze_0_0}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_xlconcat_5/microblaze_microblaze_0_xlconcat_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_xlconcat_5 || ORIG_REF_NAME==microblaze_microblaze_0_xlconcat_5}]

# IP: bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_1 || ORIG_REF_NAME==microblaze_dlmb_v10_1}]

# IP: bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_1 || ORIG_REF_NAME==microblaze_ilmb_v10_1}]

# IP: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==microblaze_dlmb_bram_if_cntlr_1}]

# IP: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==microblaze_ilmb_bram_if_cntlr_1}]

# IP: bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_lmb_bram_1 || ORIG_REF_NAME==microblaze_lmb_bram_1}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_2/microblaze_microblaze_0_axi_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_2}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_1 || ORIG_REF_NAME==microblaze_microblaze_0_1}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_xlconcat_6/microblaze_microblaze_0_xlconcat_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_xlconcat_6 || ORIG_REF_NAME==microblaze_microblaze_0_xlconcat_6}]

# IP: bd/microblaze/ip/microblaze_dlmb_v10_2/microblaze_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_2 || ORIG_REF_NAME==microblaze_dlmb_v10_2}]

# IP: bd/microblaze/ip/microblaze_ilmb_v10_2/microblaze_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_2 || ORIG_REF_NAME==microblaze_ilmb_v10_2}]

# IP: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_2/microblaze_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_dlmb_bram_if_cntlr_2}]

# IP: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_2/microblaze_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_ilmb_bram_if_cntlr_2}]

# IP: bd/microblaze/ip/microblaze_lmb_bram_2/microblaze_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_lmb_bram_2 || ORIG_REF_NAME==microblaze_lmb_bram_2}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_3/microblaze_microblaze_0_axi_intc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_3 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_3}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_2 || ORIG_REF_NAME==microblaze_microblaze_0_2}]

# IP: bd/microblaze/ip/microblaze_microblaze_0_xlconcat_7/microblaze_microblaze_0_xlconcat_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_xlconcat_7 || ORIG_REF_NAME==microblaze_microblaze_0_xlconcat_7}]

# IP: bd/microblaze/ip/microblaze_dlmb_v10_3/microblaze_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_3 || ORIG_REF_NAME==microblaze_dlmb_v10_3}]

# IP: bd/microblaze/ip/microblaze_ilmb_v10_3/microblaze_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_3 || ORIG_REF_NAME==microblaze_ilmb_v10_3}]

# IP: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_3/microblaze_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==microblaze_dlmb_bram_if_cntlr_3}]

# IP: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_3/microblaze_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==microblaze_ilmb_bram_if_cntlr_3}]

# IP: bd/microblaze/ip/microblaze_lmb_bram_3/microblaze_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_lmb_bram_3 || ORIG_REF_NAME==microblaze_lmb_bram_3}]

# IP: bd/microblaze/ip/microblaze_auto_pc_0/microblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_0 || ORIG_REF_NAME==microblaze_auto_pc_0}]

# IP: bd/microblaze/ip/microblaze_auto_pc_1/microblaze_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_1 || ORIG_REF_NAME==microblaze_auto_pc_1}]

# IP: bd/microblaze/ip/microblaze_auto_pc_2/microblaze_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_2 || ORIG_REF_NAME==microblaze_auto_pc_2}]

# IP: bd/microblaze/ip/microblaze_auto_pc_3/microblaze_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_3 || ORIG_REF_NAME==microblaze_auto_pc_3}]

# IP: bd/microblaze/ip/microblaze_auto_pc_4/microblaze_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_4 || ORIG_REF_NAME==microblaze_auto_pc_4}]

# IP: bd/microblaze/ip/microblaze_auto_pc_5/microblaze_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_5 || ORIG_REF_NAME==microblaze_auto_pc_5}]

# IP: bd/microblaze/ip/microblaze_auto_pc_6/microblaze_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_6 || ORIG_REF_NAME==microblaze_auto_pc_6}]

# IP: bd/microblaze/ip/microblaze_auto_pc_7/microblaze_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_7 || ORIG_REF_NAME==microblaze_auto_pc_7}]

# IP: bd/microblaze/ip/microblaze_auto_pc_8/microblaze_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_8 || ORIG_REF_NAME==microblaze_auto_pc_8}]

# IP: bd/microblaze/ip/microblaze_auto_pc_9/microblaze_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_9 || ORIG_REF_NAME==microblaze_auto_pc_9}]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_4/microblaze_microblaze_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_4 || ORIG_REF_NAME==microblaze_microblaze_0_4}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_4/microblaze_microblaze_0_4_ooc_debug.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_4/microblaze_microblaze_0_4_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_mig_7series_0_0/microblaze_mig_7series_0_0/user_design/constraints/microblaze_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_mig_7series_0_0 || ORIG_REF_NAME==microblaze_mig_7series_0_0}]

# XDC: bd/microblaze/ip/microblaze_mig_7series_0_0/microblaze_mig_7series_0_0/user_design/constraints/microblaze_mig_7series_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_0/microblaze_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_0 || ORIG_REF_NAME==microblaze_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_0/microblaze_dlmb_v10_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_0/microblaze_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_0 || ORIG_REF_NAME==microblaze_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_0/microblaze_ilmb_v10_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_0/microblaze_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_lmb_bram_0/microblaze_lmb_bram_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_0/microblaze_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_0/microblaze_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_0/microblaze_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_rst_mig_7series_0_100M_0/microblaze_rst_mig_7series_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==microblaze_rst_mig_7series_0_100M_0}]

# XDC: bd/microblaze/ip/microblaze_rst_mig_7series_0_100M_0/microblaze_rst_mig_7series_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==microblaze_rst_mig_7series_0_100M_0}]

# XDC: bd/microblaze/ip/microblaze_rst_mig_7series_0_100M_0/microblaze_rst_mig_7series_0_100M_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_axi_timer_0_0 || ORIG_REF_NAME==microblaze_axi_timer_0_0}]

# XDC: bd/microblaze/ip/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_axi_bram_ctrl_0_0/microblaze_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_blk_mem_gen_0_0/microblaze_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_1 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_1}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_1 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_1}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_0/microblaze_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_0 || ORIG_REF_NAME==microblaze_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_0/microblaze_microblaze_0_0_ooc_debug.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_0/microblaze_microblaze_0_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_1 || ORIG_REF_NAME==microblaze_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_1 || ORIG_REF_NAME==microblaze_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_2/microblaze_microblaze_0_axi_intc_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_2}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_2/microblaze_microblaze_0_axi_intc_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_2}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_2/microblaze_microblaze_0_axi_intc_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_1 || ORIG_REF_NAME==microblaze_microblaze_0_1}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1_ooc_debug.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_2/microblaze_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_2 || ORIG_REF_NAME==microblaze_dlmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_2/microblaze_dlmb_v10_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_2/microblaze_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_2 || ORIG_REF_NAME==microblaze_ilmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_2/microblaze_ilmb_v10_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_2/microblaze_dlmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_2/microblaze_ilmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_lmb_bram_2/microblaze_lmb_bram_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_3/microblaze_microblaze_0_axi_intc_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_3 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_3}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_3/microblaze_microblaze_0_axi_intc_3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_3 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_3}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_3/microblaze_microblaze_0_axi_intc_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_2 || ORIG_REF_NAME==microblaze_microblaze_0_2}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc_debug.xdc

# XDC: bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_3/microblaze_dlmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_3 || ORIG_REF_NAME==microblaze_dlmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_dlmb_v10_3/microblaze_dlmb_v10_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_3/microblaze_ilmb_v10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_3 || ORIG_REF_NAME==microblaze_ilmb_v10_3}] {/U0 }]/U0 ]]

# XDC: bd/microblaze/ip/microblaze_ilmb_v10_3/microblaze_ilmb_v10_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_3/microblaze_dlmb_bram_if_cntlr_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_3/microblaze_ilmb_bram_if_cntlr_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_lmb_bram_3/microblaze_lmb_bram_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_0/microblaze_auto_pc_0_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_1/microblaze_auto_pc_1_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_2/microblaze_auto_pc_2_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_3/microblaze_auto_pc_3_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_4/microblaze_auto_pc_4_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_5/microblaze_auto_pc_5_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_6/microblaze_auto_pc_6_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_7/microblaze_auto_pc_7_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_8/microblaze_auto_pc_8_ooc.xdc

# XDC: bd/microblaze/ip/microblaze_auto_pc_9/microblaze_auto_pc_9_ooc.xdc

# XDC: bd/microblaze/microblaze_ooc.xdc
