# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NoC.xdc

# Block Designs: bd/NoC_integration/NoC_integration.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration || ORIG_REF_NAME==NoC_integration}]

# IP: bd/NoC_integration/ip/NoC_integration_processing_system7_0_0/NoC_integration_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_processing_system7_0_0 || ORIG_REF_NAME==NoC_integration_processing_system7_0_0}]

# IP: bd/NoC_integration/ip/NoC_integration_axi_mem_intercon_0/NoC_integration_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_axi_mem_intercon_0 || ORIG_REF_NAME==NoC_integration_axi_mem_intercon_0}]

# IP: bd/NoC_integration/ip/NoC_integration_rst_processing_system7_0_100M_0/NoC_integration_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==NoC_integration_rst_processing_system7_0_100M_0}]

# IP: bd/NoC_integration/ip/NoC_integration_xbar_0/NoC_integration_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_xbar_0 || ORIG_REF_NAME==NoC_integration_xbar_0}]

# IP: bd/NoC_integration/ip/NoC_integration_network_interface_0_0/NoC_integration_network_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_network_interface_0_0 || ORIG_REF_NAME==NoC_integration_network_interface_0_0}]

# IP: bd/NoC_integration/ip/NoC_integration_auto_pc_0/NoC_integration_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_auto_pc_0 || ORIG_REF_NAME==NoC_integration_auto_pc_0}]

# IP: bd/NoC_integration/ip/NoC_integration_auto_pc_1/NoC_integration_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_auto_pc_1 || ORIG_REF_NAME==NoC_integration_auto_pc_1}]

# XDC: bd/NoC_integration/ip/NoC_integration_processing_system7_0_0/NoC_integration_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==NoC_integration_processing_system7_0_0 || ORIG_REF_NAME==NoC_integration_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/NoC_integration/ip/NoC_integration_rst_processing_system7_0_100M_0/NoC_integration_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==NoC_integration_rst_processing_system7_0_100M_0}]

# XDC: bd/NoC_integration/ip/NoC_integration_rst_processing_system7_0_100M_0/NoC_integration_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NoC_integration_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==NoC_integration_rst_processing_system7_0_100M_0}]

# XDC: bd/NoC_integration/ip/NoC_integration_rst_processing_system7_0_100M_0/NoC_integration_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/NoC_integration/ip/NoC_integration_xbar_0/NoC_integration_xbar_0_ooc.xdc

# XDC: bd/NoC_integration/ip/NoC_integration_auto_pc_0/NoC_integration_auto_pc_0_ooc.xdc

# XDC: bd/NoC_integration/ip/NoC_integration_auto_pc_1/NoC_integration_auto_pc_1_ooc.xdc

# XDC: bd/NoC_integration/NoC_integration_ooc.xdc
