# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/network_2x2/network_2x2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2 || ORIG_REF_NAME==network_2x2}]

# IP: bd/network_2x2/ip/network_2x2_noc_router_NE_0_0/network_2x2_noc_router_NE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_noc_router_NE_0_0 || ORIG_REF_NAME==network_2x2_noc_router_NE_0_0}]

# IP: bd/network_2x2/ip/network_2x2_noc_router_NW_0_0/network_2x2_noc_router_NW_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_noc_router_NW_0_0 || ORIG_REF_NAME==network_2x2_noc_router_NW_0_0}]

# IP: bd/network_2x2/ip/network_2x2_noc_router_SE_0_0/network_2x2_noc_router_SE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_noc_router_SE_0_0 || ORIG_REF_NAME==network_2x2_noc_router_SE_0_0}]

# IP: bd/network_2x2/ip/network_2x2_noc_router_SW_0_0/network_2x2_noc_router_SW_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_noc_router_SW_0_0 || ORIG_REF_NAME==network_2x2_noc_router_SW_0_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_0_0/network_2x2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_0_0 || ORIG_REF_NAME==network_2x2_xlconstant_0_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_1_0/network_2x2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_1_0 || ORIG_REF_NAME==network_2x2_xlconstant_1_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_2_0/network_2x2_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_2_0 || ORIG_REF_NAME==network_2x2_xlconstant_2_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_0_1/network_2x2_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_0_1 || ORIG_REF_NAME==network_2x2_xlconstant_0_1}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_1_1/network_2x2_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_1_1 || ORIG_REF_NAME==network_2x2_xlconstant_1_1}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_2_1/network_2x2_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_2_1 || ORIG_REF_NAME==network_2x2_xlconstant_2_1}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_3_0/network_2x2_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_3_0 || ORIG_REF_NAME==network_2x2_xlconstant_3_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_4_0/network_2x2_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_4_0 || ORIG_REF_NAME==network_2x2_xlconstant_4_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_5_0/network_2x2_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_5_0 || ORIG_REF_NAME==network_2x2_xlconstant_5_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_6_0/network_2x2_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_6_0 || ORIG_REF_NAME==network_2x2_xlconstant_6_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_7_0/network_2x2_xlconstant_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_7_0 || ORIG_REF_NAME==network_2x2_xlconstant_7_0}]

# IP: bd/network_2x2/ip/network_2x2_xlconstant_8_0/network_2x2_xlconstant_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xlconstant_8_0 || ORIG_REF_NAME==network_2x2_xlconstant_8_0}]

# IP: bd/network_2x2/ip/network_2x2_processing_system7_0_0/network_2x2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_processing_system7_0_0 || ORIG_REF_NAME==network_2x2_processing_system7_0_0}]

# IP: bd/network_2x2/ip/network_2x2_network_interface_0_0/network_2x2_network_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_network_interface_0_0 || ORIG_REF_NAME==network_2x2_network_interface_0_0}]

# IP: bd/network_2x2/ip/network_2x2_processing_system7_0_axi_periph_0/network_2x2_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==network_2x2_processing_system7_0_axi_periph_0}]

# IP: bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==network_2x2_rst_processing_system7_0_100M_0}]

# IP: bd/network_2x2/ip/network_2x2_network_interface_1_0/network_2x2_network_interface_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_network_interface_1_0 || ORIG_REF_NAME==network_2x2_network_interface_1_0}]

# IP: bd/network_2x2/ip/network_2x2_xbar_0/network_2x2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_xbar_0 || ORIG_REF_NAME==network_2x2_xbar_0}]

# IP: bd/network_2x2/ip/network_2x2_network_interface_2_0/network_2x2_network_interface_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_network_interface_2_0 || ORIG_REF_NAME==network_2x2_network_interface_2_0}]

# IP: bd/network_2x2/ip/network_2x2_network_interface_3_0/network_2x2_network_interface_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_network_interface_3_0 || ORIG_REF_NAME==network_2x2_network_interface_3_0}]

# IP: bd/network_2x2/ip/network_2x2_auto_pc_0/network_2x2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_auto_pc_0 || ORIG_REF_NAME==network_2x2_auto_pc_0}]

# XDC: bd/network_2x2/ip/network_2x2_processing_system7_0_0/network_2x2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==network_2x2_processing_system7_0_0 || ORIG_REF_NAME==network_2x2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==network_2x2_rst_processing_system7_0_100M_0}]

# XDC: bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==network_2x2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==network_2x2_rst_processing_system7_0_100M_0}]

# XDC: bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/network_2x2/ip/network_2x2_xbar_0/network_2x2_xbar_0_ooc.xdc

# XDC: bd/network_2x2/ip/network_2x2_auto_pc_0/network_2x2_auto_pc_0_ooc.xdc

# XDC: bd/network_2x2/network_2x2_ooc.xdc
