# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.cache/wt [current_project]
set_property parent.project_path /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/network_interface_1.0
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_SE
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_SW
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_W
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_FULL
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_E
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_N
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_NE
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_S
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_generic
  /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/ip_repo/noc_router_NW
} [current_project]
add_files /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/network_2x2.bd
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_processing_system7_0_0/network_2x2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_rst_processing_system7_0_100M_0/network_2x2_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_xbar_0/network_2x2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/ip/network_2x2_auto_pc_0/network_2x2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/network_2x2_ooc.xdc]
set_property is_locked true [get_files /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/network_2x2.bd]

read_vhdl -library xil_defaultlib /home/kjans/pc/NoC_Emulator/git/Integration/NoC_FPGA_Emulator/NoC_integration/NoC_integration.srcs/sources_1/bd/network_2x2/hdl/network_2x2_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top network_2x2_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef network_2x2_wrapper.dcp
catch { report_utilization -file network_2x2_wrapper_utilization_synth.rpt -pb network_2x2_wrapper_utilization_synth.pb }
